/**
 * M7 gate: Seasons numbers on the demo store, cross-checked against direct SQL, and the M2 story
 * (shop-api main 0.51 → 0.87 across "Tighten CLAUDE.md and add test hook") reproduced by the view.
 *
 * The demo is generated by the real generator CLI in a child process (into a temp dir outside
 * any git worktree), then ingested through the real adapter, exactly like `pnpm demo:data`.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { costUsd, median, wilsonInterval, type SeasonsView } from '@garden/core';
import {
  ClaudeCodeAdapter,
  deriveAll,
  ingest,
  loadGardenConfig,
  Redactor,
  Store,
} from '@garden/ingest';
import { createApp } from './app';

const ROOT = fileURLToPath(new URL('../../../', import.meta.url));
const AS_OF = '2026-10-01T12:00:00Z';
const dir = mkdtempSync(join(tmpdir(), 'garden-seasons-'));
let store: Store;
let pricing: ReturnType<typeof loadGardenConfig>['pricing'];
let views: SeasonsView[] = [];

beforeAll(async () => {
  const out = join(dir, 'demo');
  const manifest = JSON.parse(
    execFileSync(process.execPath, ['--import', 'tsx', 'scripts/demo/src/cli.ts', '--out', out], {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }),
  ) as { claudeHome: string; claudeJsonPath: string; gardenYamlPath: string };
  store = new Store(join(dir, 'garden.db'));
  const adapter = new ClaudeCodeAdapter(manifest);
  await ingest(adapter, store, new Redactor(Buffer.alloc(32, 7)));
  deriveAll(store, adapter.garden);
  pricing = loadGardenConfig(manifest.gardenYamlPath).pricing;
  const app = createApp({ store, asOf: AS_OF, ...(pricing ? { pricing } : {}) });
  const garden = (await (await app.request('/api/garden')).json()) as { beds: { id: string }[] };
  views = await Promise.all(
    garden.beds.map(
      async (b) => (await (await app.request(`/api/seasons/${b.id}`)).json()) as SeasonsView,
    ),
  );
}, 180_000);
afterAll(() => {
  store?.close();
  rmSync(dir, { recursive: true, force: true });
});

const LABEL = `COALESCE(m.label, o.label, 'unknown')`;
interface SqlRow {
  runs: number;
  known: number;
  credit: number | null;
  unknown: number;
  manual: number;
}
function sql(where: string, ...params: (string | null)[]): SqlRow {
  return store.db
    .prepare(
      `SELECT COUNT(*) AS runs,
              SUM(${LABEL} != 'unknown') AS known,
              SUM(CASE ${LABEL} WHEN 'success' THEN 1.0 WHEN 'partial' THEN 0.5 WHEN 'failure' THEN 0 END) AS credit,
              SUM(${LABEL} = 'unknown') AS unknown,
              SUM(m.run_id IS NOT NULL) AS manual
         FROM runs r JOIN agents a ON a.id = r.agent_id JOIN harness_families f ON f.id = r.family_id
         LEFT JOIN outcomes o ON o.run_id = r.id LEFT JOIN manual_labels m ON m.run_id = r.id
        WHERE r.started_at >= ? AND r.started_at <= ? AND ${where}`,
    )
    .get(...windowParams(), ...params) as unknown as SqlRow;
}
const windowParams = () => [views[0]!.window.from, views[0]!.window.to];
const byName = (name: string) => views.find((v) => v.bed.name === name)!;

describe('seasons on the demo store (M7 gate)', () => {
  it('every bed has seasons and every in-window run is attributed exactly once', () => {
    expect(views.length).toBe(6);
    for (const v of views) {
      expect(v.seasons.length).toBeGreaterThan(0);
      const attributed = v.series.reduce(
        (n, s) => n + s.perSeason.reduce((m, p) => m + p.runs, 0),
        0,
      );
      expect(attributed).toBe(sql('r.family_id = ?', v.familyId).runs);
    }
  });

  it('per-season rate, n, unknown, manual, CI and run count equal direct SQL', () => {
    let checked = 0;
    for (const v of views)
      for (const s of v.series)
        for (const p of s.perSeason) {
          const row = sql(
            `r.family_id = ? AND r.agent_id = ? AND r.harness_version_id = ? AND r.loop_id IS ?`,
            v.familyId,
            s.agentId,
            p.harnessVersionId,
            s.loop?.id ?? null,
          );
          expect(p.runs).toBe(row.runs);
          expect(p.success.n).toBe(row.known ?? 0);
          expect(p.success.nUnknown).toBe(row.unknown ?? 0);
          expect(p.success.nManual).toBe(row.manual ?? 0);
          if (row.known) {
            expect(p.success.value).toBeCloseTo(row.credit! / row.known, 12);
            expect(p.success.ci95).toEqual(wilsonInterval(row.credit!, row.known));
          } else expect(p.success.value).toBeNull();
          checked++;
        }
    expect(checked).toBeGreaterThan(30);
  });

  it('median cost per run equals tokens × pricing over the same SQL rows', () => {
    const v = byName('shop-api');
    for (const s of v.series)
      for (const p of s.perSeason) {
        const rows = store.db
          .prepare(
            `SELECT models_json, tok_input, tok_output, tok_cache_read, tok_cache_write_5m, tok_cache_write_1h
               FROM runs WHERE family_id = ? AND agent_id = ? AND harness_version_id = ? AND loop_id IS ?
                AND started_at >= ? AND started_at <= ?`,
          )
          .all(
            v.familyId,
            s.agentId,
            p.harnessVersionId,
            s.loop?.id ?? null,
            ...windowParams(),
          ) as Record<string, number | string>[];
        const costs = rows
          .map((r) =>
            costUsd(
              {
                input: Number(r.tok_input),
                output: Number(r.tok_output),
                cacheRead: Number(r.tok_cache_read),
                cacheWrite5m: Number(r.tok_cache_write_5m),
                cacheWrite1h: Number(r.tok_cache_write_1h),
              },
              (JSON.parse(String(r.models_json)) as string[])[0] ?? '',
              pricing,
            ),
          )
          .filter((c): c is number => c !== null);
        expect(p.costPerRunUsd).toBeCloseTo(median(costs) ?? NaN, 12);
      }
  });

  it('story: shop-api main 0.51 → 0.87 across "Tighten CLAUDE.md and add test hook", separated', () => {
    const v = byName('shop-api');
    const main = v.series.find((s) => s.agentName === 'main' && !s.loop)!;
    const chain = v.seasons.filter((s) => s.agentId === main.agentId);
    expect(chain.map((s) => s.title)).toEqual([
      'Initial commit',
      'Tighten CLAUDE.md and add test hook',
    ]);
    expect(chain[1]!.diffSummary).toEqual(
      expect.arrayContaining([
        'hooks changed',
        expect.stringMatching(/^instructions −[\d,]+ bytes/), // shrank (exact size moves with demo content)
      ]),
    );
    const [before, after] = main.perSeason;
    expect(before!.success.value!.toFixed(2)).toBe('0.51');
    expect(after!.success.value!.toFixed(2)).toBe('0.87');
    expect(after!.vsPrevious!.separated).toBe(true);
    // The M2 story query (time split at the commit, loop runs excluded) gives the same numbers.
    const at = chain[1]!.from;
    const where = `a.name = 'main' AND f.name = 'shop-api' AND r.loop_id IS NULL AND r.started_at`;
    const b = sql(`${where} < ?`, at);
    const a = sql(`${where} >= ?`, at);
    expect(before!.success.value).toBeCloseTo(b.credit! / b.known, 12);
    expect(after!.success.value).toBeCloseTo(a.credit! / a.known, 12);
    // The nightly loop has its own row and did not move: within noise.
    const loop = v.series.find((s) => s.agentName === 'main' && s.loop)!;
    expect(loop.loop!.name).toBe('nightly-flaky-triage');
    expect(loop.perSeason[1]!.vsPrevious!.separated).toBe(false);
    expect(v.caveat).toMatch(/Correlation, not causation/);
  });

  it('web-dashboard: the model switch is its own season with a generated title', () => {
    const v = byName('web-dashboard');
    const main = v.series.find((s) => s.agentName === 'main' && !s.loop)!;
    const titles = v.seasons.filter((s) => s.agentId === main.agentId).map((s) => s.title);
    expect(titles).toContain('Model: opus 5.5 → sonnet 5.5');
    expect(titles).toContain('Switch default model to sonnet');
  });

  it('unknown bed → 404', async () => {
    const app = createApp({ store, asOf: AS_OF });
    expect((await app.request('/api/seasons/fam_nope')).status).toBe(404);
    expect((await app.request('/api/seasons/fam_nope?days=0')).status).toBe(400);
  });
});
